version: '3'

services:
  app:
    image: 'chaashish/bankingapptest.jar:latest'
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - target: 8091
        x-aws-protocol: http
    depends_on:
      - db    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Comany_DB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Comany_DB
    volumes:
      - dbsaaa:/var/lib/postgresql/data
    expose:
      - "5432:5432" 
volumes:
  dbsaaa:
    external: true
    name: fs-056fe7241a510be0b  
    